### PR TITLE
Add iOS Unified project

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by AArnott** [comment]
I've created a local branch of this pull request as `onovotny-ios-unified-support`, resolved merge conflicts and am making a few more changes. I'll merge from there.

In the meantime @onovotny, please retain your branch so that github doesn't close this pull request. When I merge my branch into master, github should automatically close your PR.

**Comment by onovotny** [comment]
Awesome :+1:. Any ETA on this? I'm working on a project now that needs the unified profile in the next week or so... Thx!

**Comment by AArnott** [comment]
I'm hoping to have it done tonight or by Monday. PCLCrypto [depends](https://github.com/AArnott/PCLCrypto/blob/master/nuget/PCLCrypto.nuspec#L24) on the Validation package which needs to be updated for iOS Unified as well. So I'm working through that. Then we need to add an iOS Unified test project to PCLCrypto, which requires that PCLCommandBase and PCLTesting be updated for iOS Unified as well. So I'm working through the dependency chain.

**Comment by AArnott** [comment]
@onovotny Please try the PCLCrypto.1.0.0-beta2.nupkg file 
from [OneDrive](https://onedrive.live.com/redir?resid=63D0C265F96E43D!1379604&authkey=!AMKAUf6UQxgIxX4&ithint=file%2cnupkg) with your iOS Unified app. If it works, I'll publish it to nuget.org after merging the branch into master.

**Comment by onovotny** [comment]
Looks okay to me from a nuget packaging standpoint; I still need @dsplaisted to merge my PR to PCLStorage before I can properly test my app with Unified... For PCLCrypto, I'm mainly using the Hmac-Sha1 impl for signing Twitter OAuth requests.

**Comment by AArnott** [comment]
Just curious: would you find the NerdBank.OAuth
<https://www.nuget.org/packages/NerdBank.OAuth> package useful? It is a
very simple PCL that implements OAuth 1.0 client, and itself depends on
PCLCrypto.
I guess merging into master and shipping as beta2 won't do any harm, and
will build confidence that we intend to support iOS Unified. I'll do that
later today if I can get to it.

**Comment by onovotny** [comment]
I haven't looked at that OAuth package -- I actually started from an AppStudio-generated project (it's come a long way!) and turned it into a Xam Forms project instead of Windows Universal. It already had WinRT-api based code for generating the Twitter signing, so I just used the PCLCrypto WinRTCrypto classes and it just worked :)

BTW, the C# 6 using PCLCrypto.WinRTCrypto makes it even more brilliant as it imports all of the static properties and makes it work w/o code changes :)

**Comment by AArnott** [comment]
Ooh! That's really cool. If you can send a pull request with a README.md
change that describes that C# 6 technique that would be awesome to share.

**Comment by AArnott** [comment]
This is now published on NuGet as [beta2](http://www.nuget.org/packages/PCLCrypto/1.0.0-beta2).

**Pull request merged**
