### PR TITLE
[android] workaround to fix invalid PCLCrypto assembly

### LINKED ISSUE #138: Alpha assembly causes MSBuild failure in ResolveLibraryProjectImports task
I'm attempting to test the new prerelease build `2.1.17-alpha-g5b1e8dff8c` and am currently unable to due to an issue exposed in MSBuild. I've updated the [related issue](https://developercommunity.visualstudio.com/content/problem/164584/cant-build-android-error-msb4018-the-resolvelibrar.html) on the VS site, thought it's closed.

I have two Xamarin projects using the typical structure of `MyProject` as a NET Standard project and `MyProject.Android` for the native parts. If I reference the new PCLCrypto assembly in the base project, it builds fine. However, building the Android project, which references the base project, the build fails.

```
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
error MSB4018: System.NotSupportedException: The given path's format is not supported.
error MSB4018:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
error MSB4018:    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
error MSB4018:    at System.IO.Directory.CreateDirectory(String path)
error MSB4018:    at Xamarin.Android.Tools.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Boolean forceUpdate)
error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
```

Running VS 2017 Community 15.6.2. I'm not sure if this is technically your issue. It will make it hard to test for some people, though. Thanks!

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes #138

Unfortunately, you will need to submit a new release to NuGet with this fix.

I have submitted fixes to Xamarin.Android itself regarding this issue: https://github.com/xamarin/xamarin-android/pull/1852

### CODE REVIEW

**Comment by AArnott** [comment]
Thanks for doing all this research and supplying the fix, @jonathanpeppers. I'll merge and ship as soon as the PR build validation is successful.

**Comment by AArnott** [comment]
I don't know why appveyor is hanging on installation of dependencies. Perhaps a network outage. But I'm looking for a workaround.

**Comment by jonathanpeppers** [comment]
Let me know if you get it to produce a `nupkg`, I want to look inside and verify `monoandroid23\PCLCrypto.dll` looks right.

**Comment by AArnott** [comment]
The problem seems to be that the android SDK has stopped support automated installs and instead has an interactive prompt for the license agreement. I'm looking for workarounds.

**Comment by jonathanpeppers** [comment]
Here is an example of what we are doing for Embeddinator-4000, this is Powershell:
```
# install API 24, 26, and Google Repository (24 to be dropped)
echo "y`n" | & "C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager" "platforms;android-24" "platforms;android-26" "extras;google;m2repository"
```

I think that `android.bat` script you're calling is deprecated now, sorry 😞

**Comment by AArnott** [comment]
Thanks. Yes, I'm coming to the same conclusions. My work in progress is [here](https://github.com/AArnott/PCLCrypto/compare/UpdateDeps?expand=1). 

Thanks for the sample. That's almost what I'm doing. If my way doesn't work, I'll add the `n to my echo statement.

**Comment by jonathanpeppers** [comment]
It looks like the 2.0 branch is already using Windows directory separators, so it's probably already working: https://github.com/AArnott/PCLCrypto/blob/ef864c731f4ce667f7f5c03680800e51b606f823/src/EnlistmentInfo.props#L15-L17

**Comment by AArnott** [comment]
> Let me know if you get it to produce a nupkg, I want to look inside and verify monoandroid23\PCLCrypto.dll looks right.

I verified your fix worked on the appveyor built package.

**Comment by AArnott** [comment]
This is deploying to nuget.org right now as 2.1.27-alpha

Thanks again.

**Pull request merged**
